### ISSUE TITLE
db query error on Special:WatchAnalytics

### ISSUE THREAD

**Issue by hexmode** [enterprisemediawiki/WatchAnalytics#48]
```
A database query error has occurred. This may indicate a bug in the software.

    Query:
    INSERT INTO `watch_tracking_user` (user_id,num_watches,num_pending,tracking_timestamp) VALUES 
```

(tons of stuff deleted here)

```
    Function: WatchStateRecorder::recordAll
    Error: 1062 Duplicate entry '20160218174656-0' for key 'watch_tracking_user_datapoint' (localhost)

Backtrace:

#0 ...includes/db/Database.php(1205): DatabaseBase->reportQueryError('Duplicate entry...', 1062, 'INSERT  INTO `w...', 'WatchStateRecor...', false)
#1 ...includes/db/Database.php(2087): DatabaseBase->query('INSERT  INTO `w...', 'WatchStateRecor...')
#2 ...extensions/WatchAnalytics/includes/WatchStateRecorder.php(174): DatabaseBase->insert('watch_tracking_...', Array, 'WatchStateRecor...')
#3 ...extensions/WatchAnalytics/specials/SpecialWatchAnalytics.php(36): WatchStateRecorder->recordAll()
#4 ...includes/specialpage/SpecialPage.php(384): SpecialWatchAnalytics->execute(NULL)
#5 ...includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run(NULL)
#6 ...includes/MediaWiki.php(267): SpecialPageFactory::executePath(Object(Title), Object(RequestContext))
#7 ...includes/MediaWiki.php(566): MediaWiki->performRequest()
#8 ...includes/MediaWiki.php(414): MediaWiki->main()
#9 ...index.php(41): MediaWiki->run()
#10 {main}
```

**Comment by jamesmontalvo3** [comment]
Can you provide platform info from Special:Version?

**Comment by hexmode** [comment]
* MediaWiki: 1.25.1 (42fb6d8)

**Comment by jamesmontalvo3** [comment]
So you downloaded and installed in /extensions, added the appropriate callout to LocalSettings.php, and ran `update.php`? Then you got this after going to Special:WatchAnalytics? Is this on a totally new wiki, or are there existing users and revisions?

**Comment by hexmode** [comment]
existing... Took the dump from prod here and put it in dev.
